### ISSUE TITLE
[SERVE] two bugs that need to be fixed asap

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#30]
BUG 1. (SERVE) Bedrock players cannot see the pterodactyl password it should have an option in the config to remove that thing to hover over it since GeyserMC does not support it.

BUG 2. (HIGH) When running pterodactyl player servers you cannot add plugins by doing /menu and where even is the template folder for it?

**Comment by OpenSource03** [comment]
Bug 1: There is no hovering. Password is replaced by * every time they create server EXCEPT THE FIRST TIME. The first time a player creates a subserver, they will see their password. I'll add /ps resetpassword in the future, but until than, this is a separate issue.

Bug 2: In order to get access to plugins in /menu, you need to create a mount. A guide for that will be available soon. I don't have a pterodactyl instance rn, so I can't show you, but expect an guide on our wiki very soon.

**Comment by megatron0001** [comment]
Could you make an option to disable it in the config to show it every time they make a server?
