### ISSUE TITLE
Plugins menu does not work on pterodactyl

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#43]
It would be nice if you could an an auto mount, thanks.

**Comment by OpenSource03** [comment]
This requires a change in Pterodactyl which is coming with v2 very soon. We'll make a workaround until than soon.

**Comment by megatron0001** [comment]
Could you make an auto mount as a temp thing please.

**Comment by OpenSource03** [comment]
Hi! Below is an example how to do it.

Source should be directory of your server where all plugins are located.
Target should be left as-is.

The next beta version will contain an update you need to perform on your Pterodactyl in order to add additional API options meanwhile until Pterodactyl implements it, so it will be possible to auto-mount. **For now, you need to mount this mount to each server manually from admin interface for this to work.**

![Screenshot 2023-04-21 at 19 46 20](https://user-images.githubusercontent.com/29690431/233701552-f16c5f76-0d8d-4313-b0a0-c2db210faf0d.png)
